name: 'wer_dart'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  angular2: '2.0.0-alpha.33'
  polymer: any
  paper_elements: any

transformers:
- angular2:
    entry_points: web/main.dart
- polymer:
    entry_points: web/index.html
